import { TaskaLogo } from "@/components/branding/TaskaLogo";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAuthStore } from "@/stores/authStore";
import { zodResolver } from "@hookform/resolvers/zod";
import { ChevronLeft } from "lucide-react";
import { useForm, useWatch } from "react-hook-form";
import { useTranslation } from "react-i18next";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { z } from "zod";

export function Verify2FA() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const location = useLocation();
  const login = useAuthStore((state) => state.login);

  const email = location.state?.email as string | undefined;

  const schema = z.object({
    code: z
      .string()
      .length(6, t("auth.codeLengthError", "The code must be exactly 6 digits"))
      .regex(/^\d+$/, t("auth.codeNumericError", "Only numbers are allowed")),
    rememberDevice: z.boolean(),
  });

  type Verify2FAValues = z.infer<typeof schema>;

  const {
    register,
    handleSubmit,
    setValue,
    control,
    formState: { errors },
  } = useForm<Verify2FAValues>({
    resolver: zodResolver(schema),
    defaultValues: {
      code: "",
      rememberDevice: false,
    },
  });

  const rememberDevice = useWatch({
    control,
    name: "rememberDevice",
  });

  function onSubmit(values: Verify2FAValues) {
    console.log(`Validating code ${values.code} for ${email}`);
    console.log(`Remember this device? ${values.rememberDevice}`);

    login();
    navigate("/dashboard");
  }

  if (!email) {
    return <Navigate to="/login" replace />;
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center p-6 bg-background">
      <div className="w-full max-w-sm space-y-8">
        <div className="flex flex-col items-center space-y-4">
          <TaskaLogo iconOnly className="h-12 w-12" />
          <div className="text-center space-y-2">
            <h1 className="text-2xl font-bold tracking-tight">
              {t("auth.verify2FATitle", "Two-Step Verification")}
            </h1>
            <p className="text-sm text-muted-foreground">
              {t(
                "auth.verify2FASubtitle",
                "Enter the 6-digit code generated by your authenticator app.",
              )}
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="code" className="text-center block">
              {t("auth.verify2FACodeLabel", "Authentication Code")}
            </Label>
            <Input
              id="code"
              type="text"
              inputMode="numeric"
              maxLength={6}
              placeholder="000000"
              className="text-center text-2xl tracking-[0.5em] font-mono py-6"
              {...register("code")}
            />
            {errors.code && (
              <p className="text-xs text-destructive text-center">
                {errors.code.message}
              </p>
            )}
          </div>

          <div className="flex items-center space-x-2 justify-center">
            <Checkbox
              id="rememberDevice"
              checked={rememberDevice}
              onCheckedChange={(checked) =>
                setValue("rememberDevice", checked as boolean)
              }
            />
            <Label
              htmlFor="rememberDevice"
              className="text-sm font-medium leading-none cursor-pointer"
            >
              {t(
                "auth.verify2FARememberDevice",
                "Don't ask again on this browser",
              )}
            </Label>
          </div>

          <Button type="submit" className="w-full" size="lg">
            {t("auth.verify2FAButton", "Verify & Sign In")}
          </Button>
        </form>

        <Link
          to="/login"
          className="flex items-center justify-center text-sm text-muted-foreground hover:text-primary transition-colors"
        >
          <ChevronLeft className="mr-2 h-4 w-4" />
          {t("auth.backToLogin", "Back to Login")}
        </Link>
      </div>
    </div>
  );
}
